// -- THIS FILE IS AUTOGENERATED - DO NOT EDIT!!! ---

import ImGui
import CImGuizmo

// swiftlint:disable identifier_name

@inlinable public func ImGuizmoBeginFrame() {
    ImGuizmo_BeginFrame()
}

@inlinable public func ImGuizmoDecomposeMatrixToComponents(_ matrix: UnsafePointer<Float>!, _ translation: UnsafeMutablePointer<Float>!, _ rotation: UnsafeMutablePointer<Float>!, _ scale: UnsafeMutablePointer<Float>!) {
    ImGuizmo_DecomposeMatrixToComponents(matrix, translation, rotation, scale)
}

@inlinable public func ImGuizmoDrawCubes(_ view: UnsafePointer<Float>!, _ projection: UnsafePointer<Float>!, _ matrices: UnsafePointer<Float>!, _ matrixCount: Int32) {
    ImGuizmo_DrawCubes(view, projection, matrices, matrixCount)
}

@inlinable public func ImGuizmoDrawGrid(_ view: UnsafePointer<Float>!, _ projection: UnsafePointer<Float>!, _ matrix: UnsafePointer<Float>!, _ gridSize: Float) {
    ImGuizmo_DrawGrid(view, projection, matrix, gridSize)
}

@inlinable public func ImGuizmoEnable(_ enable: Bool) {
    ImGuizmo_Enable(enable)
}

@inlinable @discardableResult public func ImGuizmoIsOver() -> Bool {
    ImGuizmo_IsOverNil()
}

@inlinable @discardableResult public func ImGuizmoIsOver(_ op: OPERATION) -> Bool {
    ImGuizmo_IsOverOPERATION(op)
}

@inlinable @discardableResult public func ImGuizmoIsUsing() -> Bool {
    ImGuizmo_IsUsing()
}

@inlinable @discardableResult public func ImGuizmoManipulate(_ view: UnsafePointer<Float>!, _ projection: UnsafePointer<Float>!, _ operation: OPERATION, _ mode: MODE, _ matrix: UnsafeMutablePointer<Float>!, _ deltaMatrix: UnsafeMutablePointer<Float>!, _ snap: UnsafeMutablePointer<Float>!, _ localBounds: UnsafeMutablePointer<Float>!, _ boundsSnap: UnsafeMutablePointer<Float>!) -> Bool {
    ImGuizmo_Manipulate(view, projection, operation, mode, matrix, deltaMatrix, snap, localBounds, boundsSnap)
}

@inlinable public func ImGuizmoRecomposeMatrixFromComponents(_ translation: UnsafePointer<Float>!, _ rotation: UnsafePointer<Float>!, _ scale: UnsafePointer<Float>!, _ matrix: UnsafeMutablePointer<Float>!) {
    ImGuizmo_RecomposeMatrixFromComponents(translation, rotation, scale, matrix)
}

@inlinable public func ImGuizmoSetDrawlist(_ drawlist: UnsafeMutablePointer<ImDrawList>!) {
    ImGuizmo_SetDrawlist(drawlist)
}

@inlinable public func ImGuizmoSetID(_ id: Int32) {
    ImGuizmo_SetID(id)
}

@inlinable public func ImGuizmoSetOrthographic(_ isOrthographic: Bool) {
    ImGuizmo_SetOrthographic(isOrthographic)
}

@inlinable public func ImGuizmoSetRect(_ x: Float, _ y: Float, _ width: Float, _ height: Float) {
    ImGuizmo_SetRect(x, y, width, height)
}

@inlinable public func ImGuizmoViewManipulate(_ view: UnsafeMutablePointer<Float>!, _ length: Float, _ position: ImVec2, _ size: ImVec2, _ backgroundColor: ImU32) {
    ImGuizmo_ViewManipulate(view, length, position, size, backgroundColor)
}

@inlinable public func ImGuizmoGetRayOrigin(_ pOut: UnsafeMutablePointer<ImVec4>!) -> Void {
    ImGuizmo_GetRayOrigin(pOut)
}

@inlinable public func ImGuizmoGetRayVector(_ pOut: UnsafeMutablePointer<ImVec4>!) -> Void {
    ImGuizmo_GetRayVector(pOut)
}
